apiVersion: apps/v1
kind: Deployment
metadata:
  name: mood-analyzer
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: mood-analyzer
    apps.tanzu.vmware.com/workload-type: dekt-worker
    app.kubernetes.io/component: run
    carto.run/workload-name: mood-analyzer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: mood-analyzer
      apps.tanzu.vmware.com/workload-type: dekt-worker
      carto.run/workload-name: mood-analyzer
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: mood-analyzer
        apps.tanzu.vmware.com/workload-type: dekt-worker
        carto.run/workload-name: mood-analyzer
    spec:
      containers:
      - image: registry.dekt.io/dekt-dev/mood-analyzer-myteam@sha256:cfd9f498d8531ed9a1d3a7ed9dee4a7e779296e96d1e4727f79e3f0d35d4f49c
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

